resources:
 pipelines:
   - pipeline: P1
     source: Arsasana.Test2
  #  - pipeline: P4
  #    source: Arsasana.Test1

trigger:
- master
stages:
 - stage: ProduceArtifact
   jobs:
     - job: J4
       pool: 
        name: Default
       steps:
         - download: P1
           artifact: A1.1

